version: "3.7"

services:
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   # container_name: "prisma"
    
  #   # Uncomment for open ports
  #   # ports:
  #     # - '4466:4466'
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       databases:
  #         default:
  #           connector: mysql
  #           host: ${MYSQL_HOST:-mysql}
  #           port: ${MYSQL_PORT:-3306}
  #           # database: ${MYSQL_DB}
  #           user: ${MYSQL_USER:-root}
  #           password: ${MYSQL_PASSWORD}
  #           migrations: ${PRISMA_MIGRATIONS}
  #           rawAccess: ${PRISMA_RAW_ACCESS}
  #   # depends_on:
  #   #   - mysql

  prisma:
    image: prismagraphql/prisma:1.34
    # container_name: "k12_prisma"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${PG_HOST:-postgres}
            port: ${PG_PORT:-5432}
            user: ${POSTGRES_USER:-prisma}
            password: ${POSTGRES_PASSWORD:-prisma}

  postgres:
    image: kartoza/postgis:12.0
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${POSTGRES_DB:-prisma}
      - POSTGRES_USER=${POSTGRES_USER:-prisma}
      - POSTGRES_PASS=${POSTGRES_PASSWORD:-prisma}
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting

  pgadmin:
    image: dpage/pgadmin4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # Can set another path 
      - mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST:-mysql}
      PMA_PORT: ${MYSQL_PORT:-3306}
      UPLOAD_LIMIT: ${PMA_UPLOAD_LIMIT:-100M}
    # depends_on:
    #   - mysql

  front:
    tty: true
    build:
      context: ./prisma-cms
      network: ${NETWORK_NAME:-prisma-cms-default}
      args: 
        - SITE=${SITE:-boilerplate}
        - ROLE=FRONT
        - ENV_MODE=development
        - endpoint=${dev_endpoint}
    volumes:
      # - schema:/www/${SITE:-boilerplate}/src/schema
      # - shared:/www/${SITE:-boilerplate}/shared
      - ./prisma-cms/${SITE:-boilerplate}/shared:/www/${SITE:-boilerplate}/shared
      - ./prisma-cms/${SITE:-boilerplate}/uploads:/www/${SITE:-boilerplate}/uploads
    # environment: 
    env_file: 
      - .env
    environment: 
      - API_ENDPOINT=${API_ENDPOINT:-http://api:4000}
      - ENV_MODE=development
    # entrypoint: /usr/bin/entrypoint-front.sh

  api:
    tty: true
    build:
      context: ./prisma-cms
      network: ${NETWORK_NAME:-prisma-cms-default}
      args: 
        - SITE=${SITE:-boilerplate}
        - ROLE=API
        - ENV_MODE=development
        - endpoint=${dev_endpoint}
        - SIGNUP_SET_NOTIFICATIONS=${SIGNUP_SET_NOTIFICATIONS:-true}
        - API_SEED_TEMPLATES=${API_SEED_TEMPLATES:-false}
        - API_SUDO_USER_USERNAME=${API_SUDO_USER_USERNAME}
    volumes:
      # - schema:/www/${SITE:-boilerplate}/src/schema
      - ./prisma-cms/${SITE:-boilerplate}/uploads:/www/${SITE:-boilerplate}/uploads

      # For any server config files, for example DKIM
      - ./opt:/opt
    # depends_on:
    #   - prisma
    env_file: 
      - .env
    environment: 
      - API_ENDPOINT=${API_ENDPOINT:-http://api:4000}
      - endpoint=${dev_endpoint}
      - GethServer=${ETHEREUM_GATEWAY:-https://cloudflare-eth.com}
    # entrypoint: /usr/bin/entrypoint-api.sh

  # web-server
  proxy:
    environment:
      - ACME_AGREE=true
    build:
      context: ./caddy
  
  # mail-server
  mail:
    image: mailhog/mailhog

volumes:
  mysql:
  postgres:
  # schema:
  # shared:

networks:
  default:
    name: ${NETWORK_NAME:-prisma-cms-default}
