version: "3.7"

services:

  prisma:
    ports:
      - '4466:4466'

  mysql:
    ports:
      - '3306:3306'

  front:
    volumes:
      - ./prisma-cms/${SITE:-boilerplate}/src:/www/${SITE:-boilerplate}/src
    command: bash -c "yarn deploy && yarn start"

  api:
    volumes:
      - ./prisma-cms/${SITE:-boilerplate}/src:/www/${SITE:-boilerplate}/src
    environment: 
      - SendmailTest=true
    command: bash -c "yarn deploy && yarn start-server-dev"

  proxy:
    ports:
      - 2015:2015
      - 2016:2016
      - 2017:2017

  pma:
    ports:
      - 8090:80

  mail:
    ports:
      - 8025:8025
